name: 💡 Feature Request
description: Suggest an idea for ON1Builder
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please fill out this form as completely as possible to help us understand your idea.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check the following before submitting a feature request
      options:
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have read the documentation to confirm this feature doesn't already exist
          required: true
        - label: This is a single feature (not multiple features combined)
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - New Trading Strategy
        - Performance Improvement
        - Security Enhancement
        - User Interface
        - Monitoring/Analytics
        - Chain Integration
        - Protocol Integration
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternative approaches could be..."

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Improved performance
        - Better user experience
        - ON1Builder security
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: How would you rate the impact of this feature?
      options:
        - Critical (Significantly improves core functionality)
        - High (Important improvement to existing features)
        - Medium (Nice to have, quality of life improvement)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have any technical details or implementation ideas, please share them
      placeholder: "Technical considerations, architecture changes, etc."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: "Any other relevant information..."

  - type: dropdown
    id: availability
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - Yes, I can implement this feature
        - Yes, I can help with testing
        - Yes, I can help with documentation
        - No, I cannot contribute at this time
    validations:
      required: true
